@startuml parser
skinparam DefaultFontName "Ubuntu Mono"

scale 20

start

if( usr has set help docs?) then (no)
    :generate the help docs automatically;
endif

if(usr has set version?) then (no)
    :generate the version automatically;
endif

while(the param list has elems?)
    :get an element;
    if(the element is an option?) then (yes)
        if(the option is valid) then(yes)
            if(the option is 'help' or 'version'?) then(yes)
                stop
            endif
            :record the name and index;
        else (no)
            stop
        endif
    endif
endwhile

:generate the valid options list;

if(have all required options been passed?) then(no)
    stop
endif

:get string vector for each option;
:pass the string vector to options;
:pase over;
stop

@enduml